modLoader="javafml"
loaderVersion="[32,)"
license = "MIT"

[[mods]]
    modId="vampirism-addon-example"
    namespace="vampirism-addon-example"
    version="${version}"
    displayName="Vampirism-Addon-Example"
    authors="Maxanier"
    description="Example"
    [[dependencies.vampirism-addon-example]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.vampirism-addon-example]]
        modId="vampirism"
        mandatory=true
        versionRange="[${vampirism_version},)"
        ordering="AFTER"
        side="BOTH"
